- EmbedSnap.php
Removes the breaking comma on line 63
> Remove breaking comma

- EmbedSnap.php
This generates error messages for missing values.
> Error messages for missing values.

- i18n/en.json
In other words, adding myself. 😜
> Proper credits

- README.md
> Small Readme Changes

- EmbedSnap.php
This adds comments to the code.
> Comment code Part 1

- README.md
This adds the filesystem in the readme.
> Filesystem in readme

- EmbedSnap.php
- i18n/en.json
This uses translatable strings for errors.
> Use translatable strings for errors

- README.md
- extension.json
- i18n/bn.json
- i18n/eo.json
- i18n/it.json
Note, please target most changes to v2.
> Update from master

- EmbedSnap.php
This is untested, although it does pass on PHP. It still needs a check to see if the value is either true or false, not something different.
> Edit Button

- EmbedSnap.php
- README.md
Registers new ``<snap-project>`` tag and makes a minor update to the comment.
> Register <snap-project> tag

- i18n/bn.json
- i18n/eo.json
- i18n/it.json
- i18n/pl.json
- i18n/qqq.json
Author names in all files should have contributors to the files not the code.
> Remove "mw-embedScratch contributors" from Author List and Add Translators' Names

- EmbedSnap.php
Adds title and author toggling feature and makes minor positioning changes to the code docs.
> Allow Title And Author Toggling

- EmbedSnap.php
Add pause button toggling feature. It will be true by default.
> Allow Pause Button Toggling

- EmbedSnap.php
This will change the visibility of this function to public.
> Make renderEmbedSnap a Public Static Function

- extension.json
Backports the above mentioned commit to the v2.1.0 branch.
> Fix messed up formatting in Special:Version

- .github/workflows/php.yml
MediaWiki may add support for it and Miraheze is planning to add it, too.
> Add checks for PHP 8.x

- EmbedSnap.php
- README.md
- extension.json
Adds support for "hiding" projects using the HTML ``details`` and ``summary`` tags.
> Add Support for "Hiding" Projects

- .gitignore
- .phan/config.php
- composer.json
- composer.lock
Sets up Phan and will fix issues if any detected as well.
> Set Up Phan

- .github/workflows/ci.yml
- composer.json
- composer.lock
Sets up PHP Parallel Lint and resolves #27.
> Set Up PHP Parallel Lint

- .github/workflows/ci.yml
- composer.json
- composer.lock
Backports CI changes to V2.5.1.
> Backport CI changes to V2.5.1

- includes/EmbedSnap.php
> Close page fixes

- extension.json
Removes unnecessary lines from extension.json.
> Remove unnecessary lines

- README.md
- composer.json
- composer.lock
- extension.json
- i18n/bn.json
- i18n/en.json
- i18n/eo.json
- i18n/it.json
- i18n/pl.json
- includes/EmbedSnap.php
> Backport "Do not apply style through i18n keys "

- extension.json
- includes/EmbedSnap.php
- phpcs.xml
> Backport master commits to ``v2``
